#!/usr/bin/env python3
"""Discover extra ArcGIS REST services via the ArcGIS Online search API.

The catalog crawl in `harvest.py` samples whatever a portal lists first, which
under-covers niche field types (GUID, Single) and geometry kinds. This script
queries ArcGIS Online for popular, public Feature Services and writes their
explicit FeatureServer URLs to `extra-services.txt`, which `harvest.py
--services-file` then probes.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "extra-services.txt"
SEARCH = "https://www.arcgis.com/sharing/rest/search"

QUERIES = [
    'type:"Feature Service"',
    'type:"Feature Service" AND (owner:esri OR owner:Esri)',
]


def search(query: str, num: int) -> list[str]:
    params = urlencode({"q": query, "f": "json", "num": num, "sortField": "numviews", "sortOrder": "desc"})
    request = Request(f"{SEARCH}?{params}", headers={"User-Agent": "SpatialEngine-ArcGisRestResearch/1.0"})
    with urlopen(request, timeout=30) as response:  # noqa: S310 - fixed https host
        body = json.load(response)
    urls = []
    for result in body.get("results", []):
        url = (result.get("url") or "").rstrip("/")
        if url.endswith("FeatureServer") and url.isascii():
            urls.append(url)
    return urls


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--num", type=int, default=100)
    parser.add_argument("--max", type=int, default=40)
    args = parser.parse_args()

    seen: list[str] = []
    for query in QUERIES:
        for url in search(query, args.num):
            if url not in seen:
                seen.append(url)
    selected = seen[: args.max]
    header = "# Generated by discover_agol.py - public ArcGIS Online Feature Services.\n"
    OUT.write_text(header + "\n".join(selected) + "\n", "utf-8")
    print(f"wrote {len(selected)} services to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
