using Spatial.Core.Features;
using Spatial.Core.Geometry;
using Spatial.PluginSdk;
using Spatial.PluginSdk.Providers;
using Spatial.Provider.PostGIS.Core;

namespace Spatial.Provider.PostGIS.Tests;

/// <summary>
/// The pure ingest planning rules (ADR-0041 §3): identity modes, table DDL,
/// schema consistency and validation. No database is involved.
/// </summary>
public sealed class PostgisIngestPlanTests
{
    private static readonly FeatureSchema GeometryOnly = FeatureTests.Schema(
        ("name", AttributeKind.String, true),
        ("geom", AttributeKind.Geometry, true));

    private static FeatureBatch Batch(FeatureSchema schema, params Feature[] features) => new(schema, features);

    private static Feature Point(FeatureSchema schema, string id, string name, double x, double y) =>
        FeatureTests.Feature(
            id, schema, name, GeometryFactory.CreatePoint(x, y, CoordinateReference.Epsg(4326)));

    [Fact]
    public void Auto_adds_a_generated_identity_primary_key_and_reports_the_column()
    {
        var plan = PostgisIngestPlan.Create(
            new IngestRequest("public.upload", 4326),
            [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]);

        Assert.Equal(IngestIdentity.Auto, plan.Identity);
        Assert.Equal("id", plan.IdentityColumn);
        Assert.Equal(1, plan.FeatureCount);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", plan.CreateTableSql());
        Assert.Equal(
            "CREATE TABLE \"public\".\"upload\" (\"name\" text, \"geom\" geometry(Geometry, 4326), \"id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
            plan.CreateTableSql());
    }

    [Fact]
    public void Auto_rejects_a_schema_that_already_has_an_id_field()
    {
        var schema = FeatureTests.Schema(
            ("id", AttributeKind.Int64, false),
            ("geom", AttributeKind.Geometry, true));
        var feature = FeatureTests.Feature("1", schema, 7L, GeometryFactory.CreatePoint(1, 2, CoordinateReference.Epsg(4326)));

        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(new IngestRequest("public.upload", 4326), [Batch(schema, feature)]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
        Assert.Contains("Identity=Source", failure.Message);
    }

    [Fact]
    public void Auto_rejects_an_identity_field()
    {
        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(
                new IngestRequest("public.upload", 4326, IngestIdentity.Auto, "name"),
                [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
    }

    [Fact]
    public void Source_uses_the_named_field_as_the_primary_key()
    {
        var schema = FeatureTests.Schema(
            ("code", AttributeKind.Int64, false),
            ("geom", AttributeKind.Geometry, true));

        var plan = PostgisIngestPlan.Create(
            new IngestRequest("public.upload", 4326, IngestIdentity.Source, "code"),
            [Batch(schema, FeatureTests.Feature("1", schema, 7L, GeometryFactory.CreatePoint(1, 2, CoordinateReference.Epsg(4326))))]);

        Assert.Equal("code", plan.IdentityColumn);
        Assert.Contains("PRIMARY KEY (\"code\")", plan.CreateTableSql());
        Assert.DoesNotContain("IDENTITY", plan.CreateTableSql());
    }

    [Fact]
    public void Source_requires_an_existing_int64_field()
    {
        var missing = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(
                new IngestRequest("public.upload", 4326, IngestIdentity.Source, "code"),
                [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]));
        Assert.Contains("not a field", missing.Message);

        var wrongKind = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(
                new IngestRequest("public.upload", 4326, IngestIdentity.Source, "name"),
                [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]));
        Assert.Contains("Int64", wrongKind.Message);

        var absent = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(
                new IngestRequest("public.upload", 4326, IngestIdentity.Source),
                [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]));
        Assert.Contains("IdentityField", absent.Message);
    }

    [Fact]
    public void None_creates_a_data_only_table()
    {
        var plan = PostgisIngestPlan.Create(
            new IngestRequest("public.upload", 4326, IngestIdentity.None),
            [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]);

        Assert.Null(plan.IdentityColumn);
        Assert.DoesNotContain("PRIMARY KEY", plan.CreateTableSql());
    }

    [Fact]
    public void None_rejects_an_identity_field()
    {
        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(
                new IngestRequest("public.upload", 4326, IngestIdentity.None, "name"),
                [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
    }

    [Fact]
    public void Feature_count_sums_every_page()
    {
        var plan = PostgisIngestPlan.Create(
            new IngestRequest("public.upload", 4326),
            [
                Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2), Point(GeometryOnly, "2", "b", 3, 4)),
                Batch(GeometryOnly, Point(GeometryOnly, "3", "c", 5, 6)),
            ]);

        Assert.Equal(3, plan.FeatureCount);
    }

    [Theory]
    [InlineData("UPPER.case")]
    [InlineData("public.upload;drop")]
    [InlineData("")]
    public void An_invalid_dataset_identifier_is_rejected(string dataset)
    {
        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(new IngestRequest(dataset, 4326), [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
    }

    [Fact]
    public void A_non_positive_srid_is_rejected()
    {
        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(new IngestRequest("public.upload", 0), [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2))]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
    }

    [Fact]
    public void An_empty_ingest_is_rejected()
    {
        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(new IngestRequest("public.upload", 4326), [Batch(GeometryOnly)]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
    }

    [Fact]
    public void Pages_must_share_the_first_page_schema()
    {
        var other = FeatureTests.Schema(("other", AttributeKind.String, true), ("geom", AttributeKind.Geometry, true));

        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(
                new IngestRequest("public.upload", 4326),
                [Batch(GeometryOnly, Point(GeometryOnly, "1", "a", 1, 2)), Batch(other)]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
    }

    [Fact]
    public void A_field_name_that_is_not_a_valid_identifier_is_rejected()
    {
        var schema = FeatureTests.Schema(
            ("has space", AttributeKind.String, true),
            ("geom", AttributeKind.Geometry, true));

        var failure = Assert.Throws<SpatialException>(() =>
            PostgisIngestPlan.Create(
                new IngestRequest("public.upload", 4326),
                [Batch(schema, FeatureTests.Feature("1", schema, "x", GeometryFactory.CreatePoint(1, 2, CoordinateReference.Epsg(4326))))]));

        Assert.Equal(SpatialException.InvalidArguments, failure.Code);
        Assert.Contains("not a valid identifier", failure.Message);
    }
}
