<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Spatial.Core\Spatial.Core.csproj" />
    <ProjectReference Include="..\..\conformance\Spatial.PredicateConformance\Spatial.PredicateConformance.csproj" />
    <ProjectReference Include="..\..\..\src\Spatial.Querying\Spatial.Querying.csproj" />
    <ProjectReference Include="..\..\conformance\Spatial.QueryConformance\Spatial.QueryConformance.csproj" />
    <ProjectReference Include="..\..\conformance\Spatial.WriteConformance\Spatial.WriteConformance.csproj" />
    <ProjectReference Include="..\..\..\src\Spatial.Contracts\Spatial.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\Spatial.Stores.Memory\Spatial.Stores.Memory.csproj" />
  </ItemGroup>

</Project>
